### ISSUE TITLE
Game crashes with brotherEdition=false

### ISSUE THREAD

**Issue by Similacrest** [TrueHorse/Enchantment-Preservation#1]
Minecraft version: 1.19.2

Fabric API 0.62.0+1.19.2, no other mods.

```
[17:22:09] [Render thread/ERROR]: Unhandled game exception
java.lang.IllegalStateException: Some intrusive holders were not added to registry: [Reference{null=air}, Reference{null=air}, Reference{null=air}]
	at net.minecraft.class_2370.method_40276(class_2370.java:352) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_40292(class_2378.java:404) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.handler$zgc001$onStart(class_310.java:4986) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:747) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
[17:22:09] [Render thread/INFO]: Stopping!
[17:22:11] [Render thread/ERROR]: Shutdown failure!
java.util.ConcurrentModificationException: null
	at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?]
	at net.minecraft.class_1060.close(class_1060.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.close(class_310.java:1092) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1490(class_310.java:1068) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:260) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
```

**Comment by TrueHorse** [comment]
Forgot to test that. 😅 Thank you for reporting it.

**Comment by TrueHorse** [comment]
There wasn't an easy way to fix it so I removed brotherEdition for the new version and made something separate for my brother. ;)
